name: Build Rustlet

on:
  workflow_call:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  GH_PROJECT_NAME: rustlet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Set image tag
        id: imagetag
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "IMAGE_TAG=${TAG_NAME}" >> $GITHUB_ENV
          else
            SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
            echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build container image
        run: |
          podman build -t $GH_PROJECT_NAME:$IMAGE_TAG .

      - name: Push image
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "${{ secrets.CR_PASSWORD }}" | podman login -u "${{ secrets.CR_USERNAME }}" --password-stdin ${{ vars.CR_REGISTRY }}
          podman tag $GH_PROJECT_NAME:$IMAGE_TAG ${{ vars.CR_REGISTRY }}/$GH_PROJECT_NAME:$IMAGE_TAG
          podman push ${{ vars.CR_REGISTRY }}/$GH_PROJECT_NAME:$IMAGE_TAG